{{- if and .Values.rbac.create .Values.operator.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openldap-operator.leaderElectionRoleBindingName" . }}
  namespace: {{ include "openldap-operator.namespace" . }}
  labels:
    {{- include "openldap-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openldap-operator.leaderElectionRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "openldap-operator.serviceAccountName" . }}
  namespace: {{ include "openldap-operator.namespace" . }}
{{- end }}
