name: Build and Release
on:
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: hansfischer
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Docker meta
        id: tag_names
        uses: docker/metadata-action@v5
        with:
          images: |
            hansfischer/openldap-operator
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Get current epoch time
        id: time
        run: echo "epoch=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Containerfile
          context: .
          build-args: |
            BUILD_NUMBER=${{ github.ref_name }}
            GIT_COMMIT=${{ github.sha }}
            BUILD_TIME=${{ steps.time.outputs.epoch }}
          platforms: linux/amd64  # ,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tag_names.outputs.tags }}
          labels: ${{ steps.tag_names.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release-helm:
    name: Release Helm Chart
    needs: build
    runs-on: self-hosted
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Update Chart Version
        run: |
          # Extrahiere Version aus dem Release-Tag (ohne 'v' Prefix)
          VERSION=${GITHUB_REF_NAME#v}
          # Aktualisiere Chart und App Version
          sed -i "s/^version:.*$/version: ${VERSION}/" deploy/helm/openldap-operator/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: \"${VERSION}\"/" deploy/helm/openldap-operator/Chart.yaml
          # Aktualisiere Image Tag in values.yaml
          sed -i "s/^  tag:.*$/  tag: \"${VERSION}\"/" deploy/helm/openldap-operator/values.yaml

      - name: Create Helm Package
        run: |
          cd deploy/helm
          helm package openldap-operator/
          mkdir -p repo
          mv *.tgz repo/
          # Erstelle tempor채ren Index f체r das neue Chart
          helm repo index repo/ --url https://guided-traffic.github.io/openldap-operator/
          cd ../..

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Save Chart Package
        run: |
          mkdir -p /tmp/helm-charts
          cp -r deploy/helm/repo/* /tmp/helm-charts/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Pages
        run: |
          # Kopiere neue Charts ins Root-Verzeichnis
          cp /tmp/helm-charts/*.tgz .

          # Merge mit existierendem index.yaml falls vorhanden
          if [ -f index.yaml ]; then
            # Erstelle tempor채ren Ordner f체r Merge
            mkdir -p temp-repo
            cp *.tgz temp-repo/
            # Merge mit existierendem Index
            helm repo index temp-repo/ --url https://guided-traffic.github.io/openldap-operator/ --merge index.yaml
            cp temp-repo/index.yaml .
            rm -rf temp-repo
          else
            # Erstelle neuen Index falls keiner existiert
            helm repo index . --url https://guided-traffic.github.io/openldap-operator/
          fi

          git add --force *.tgz index.yaml
          git commit -m "Release Helm chart for $GITHUB_REF_NAME"
          git push --force origin gh-pages

      - name: Update Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
            index.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
